version: '3.8'

services:
  flashp:
    image: node:20-alpine
    container_name: flashp_app
    working_dir: /app
    command: sh -c "npm install && npm run build && npm start"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    restart: always
